"""Módulo compartido con constantes, utilidades y componentes."""

from src.shared.constants import (
    DATASETS_PATH,
    METADATA_PATH,
    CAREERS_FILE,
    STATISTICS_METADATA_FILE,
    METADATA_SHEET_PREFIX,
    STATE_COLORS,
    STATE_LABELS,
    STATE_ORDER,
    THEORY_COMPONENT_COLORS,
    PRACTICAL_COMPONENT_COLORS,
    TOTALS_COMPONENT_COLORS,
    TOPIC_COLORS,
    EXAM_LABELS,
    VALID_KNOWLEDGES,
    KNOWLEDGE_LABEL_FIXES,
)

from src.shared.utils import (
    load_available_datasets,
    extract_semester_name,
    load_data,
    get_dataset_map,
    get_default_semester,
    load_careers_catalog,
    load_historical_data,
    load_topic_max_map_for_semester,
    load_practical_max_map_for_semester,
    load_topic_knowledge_map_for_semester,
    extract_topic_base,
    group_topic_columns_by_base,
    format_knowledge_list,
    semester_sort_key,
    build_semester_options,
    apply_filters,
    apply_historical_filters,
    valid_exam_mask,
    mean_exam,
    component_to_exam,
    init_session_state_defaults,
)

from src.shared.components import (
    render_sidebar_single_semester,
    render_sidebar_historical,
    render_main_metrics,
    render_historical_main_metrics,
    build_state_distribution_df,
    render_state_distribution_chart,
    render_state_distribution_table,
    render_sit_distribution,
    render_students_by_career_and_state,
    render_approved_percentage_by_career,
    render_totals,
    render_theory,
    render_practical,
    render_topics,
    build_historical_state_distribution,
    render_historical_state_chart,
    render_historical_state_table,
    render_historical_student_counts_chart,
)